/**
 * blockchain-sync.js — HerbChain Backend Blockchain Integration
 * ═══════════════════════════════════════════════════════════════
 * Node.js service that:
 *  1. Connects to the deployed Provenance contract via ethers.js
 *  2. Reads on-chain events and syncs them to Supabase
 *  3. Provides Express API endpoints for frontend to trigger transactions
 *     through a trusted backend signer (avoids private-key exposure in browser)
 *
 * Usage:
 *   node blockchain-sync.js                    # starts express + event listener
 *   SYNC_ONLY=1 node blockchain-sync.js       # sync existing events then exit
 */

"use strict";

require("dotenv").config();

const { ethers }      = require("ethers");
const { createClient} = require("@supabase/supabase-js");
const express         = require("express");
const cors            = require("cors");
const fs              = require("fs");
const path            = require("path");

// ─── Config ──────────────────────────────────────────────────────────────────

const config = {
  rpcUrl:          process.env.RPC_URL          || "http://127.0.0.1:8545",
  contractAddress: process.env.CONTRACT_ADDRESS || process.env.VITE_HERB_REGISTRY_ADDRESS,
  privateKey:      process.env.BACKEND_PRIVATE_KEY,      // optional — for server-side tx
  supabaseUrl:     process.env.SUPABASE_URL     || process.env.VITE_SUPABASE_URL,
  supabaseKey:     process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_ANON_KEY,
  port:            parseInt(process.env.PORT)   || 3001,
};

// Guard
if (!config.contractAddress) {
  console.error("❌  CONTRACT_ADDRESS or VITE_HERB_REGISTRY_ADDRESS must be set in .env");
  process.exit(1);
}
if (!config.supabaseUrl || !config.supabaseKey) {
  console.error("❌  SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY (or anon key) must be set");
  process.exit(1);
}

// ─── Clients ─────────────────────────────────────────────────────────────────

const provider = new ethers.JsonRpcProvider(config.rpcUrl);
const supabase = createClient(config.supabaseUrl, config.supabaseKey);

// Load ABI from the artifact generated by Hardhat deploy script
function loadABI() {
  const abiPath = path.join(
    __dirname, "..", "src", "contracts", "ProvenanceABI.json"
  );
  if (!fs.existsSync(abiPath)) {
    throw new Error(`ABI file not found at ${abiPath}. Run the deploy script first.`);
  }
  const raw = JSON.parse(fs.readFileSync(abiPath, "utf8"));
  return raw.abi ?? raw;
}

let _contract = null;
function getContract(signerOrProvider) {
  const abi = loadABI();
  return new ethers.Contract(config.contractAddress, abi, signerOrProvider ?? provider);
}

// Optional: backend signer for server-side transactions
function getSignerContract() {
  if (!config.privateKey) {
    throw new Error("BACKEND_PRIVATE_KEY is not set — cannot send transactions from backend");
  }
  const wallet = new ethers.Wallet(config.privateKey, provider);
  return getContract(wallet);
}

// ─── Supabase Helpers ─────────────────────────────────────────────────────────

async function upsertBlockchainRecord(table, record, conflictOn) {
  const { error } = await supabase
    .from(table)
    .upsert(record, { onConflict: conflictOn, ignoreDuplicates: false });
  if (error) {
    console.error(`[Supabase] Error upserting into ${table}:`, error.message);
    return false;
  }
  return true;
}

/** Store a transaction hash against an existing Supabase record */
async function storeTxHash(table, matchColumn, matchValue, txHash) {
  const { error } = await supabase
    .from(table)
    .update({ tx_hash: txHash, blockchain_synced: true, synced_at: new Date().toISOString() })
    .eq(matchColumn, matchValue);

  if (error) {
    console.error(`[Supabase] storeTxHash error (${table}):`, error.message);
  } else {
    console.log(`[Supabase] ✅ Stored tx hash in ${table} where ${matchColumn}=${matchValue}`);
  }
}

// ─── Event Handlers ────────────────────────────────────────────────────────────

async function onBatchCreated(batchId, herbName, collector, harvestDate, isSustainable, event) {
  console.log(`\n[Event] BatchCreated  batchId=${batchId.slice(0, 12)}… herb=${herbName}`);
  await upsertBlockchainRecord("blockchain_batches", {
    batch_id:       batchId,
    herb_name:      herbName,
    collector:      collector.toLowerCase(),
    harvest_date:   new Date(Number(harvestDate) * 1000).toISOString(),
    is_sustainable: isSustainable,
    tx_hash:        event.log.transactionHash,
    block_number:   Number(event.log.blockNumber),
    created_at:     new Date().toISOString(),
  }, "batch_id");
}

async function onCollectionRecorded(batchId, collector, herbSpecies, timestamp, event) {
  console.log(`[Event] CollectionRecorded  batchId=${batchId.slice(0, 12)}…`);
  await upsertBlockchainRecord("blockchain_collections", {
    batch_id:     batchId,
    collector:    collector.toLowerCase(),
    herb_species: herbSpecies,
    recorded_at:  new Date(Number(timestamp) * 1000).toISOString(),
    tx_hash:      event.log.transactionHash,
    block_number: Number(event.log.blockNumber),
    created_at:   new Date().toISOString(),
  }, "batch_id");
}

async function onProcessingStepAdded(batchId, processType, processorAddr, stepIndex, timestamp, event) {
  console.log(`[Event] ProcessingStepAdded batchId=${batchId.slice(0, 12)}… step=${stepIndex}`);
  const processNames = ["DRYING", "GRINDING", "STORAGE", "EXTRACTION", "SORTING", "PACKAGING"];
  await upsertBlockchainRecord("blockchain_processing_steps", {
    batch_id:     batchId,
    step_index:   Number(stepIndex),
    process_type: processNames[Number(processType)] ?? "UNKNOWN",
    processor:    processorAddr.toLowerCase(),
    recorded_at:  new Date(Number(timestamp) * 1000).toISOString(),
    tx_hash:      event.log.transactionHash,
    block_number: Number(event.log.blockNumber),
    created_at:   new Date().toISOString(),
  }, "batch_id, step_index");
}

async function onQualityTestRecorded(batchId, lab, passed, pesticideLevel, moistureContent, timestamp, event) {
  console.log(`[Event] QualityTestRecorded batchId=${batchId.slice(0, 12)}… passed=${passed}`);
  await upsertBlockchainRecord("blockchain_quality_tests", {
    batch_id:         batchId,
    lab_address:      lab.toLowerCase(),
    passed:           passed,
    pesticide_level:  Number(pesticideLevel),
    moisture_content: Number(moistureContent),
    recorded_at:      new Date(Number(timestamp) * 1000).toISOString(),
    tx_hash:          event.log.transactionHash,
    block_number:     Number(event.log.blockNumber),
    created_at:       new Date().toISOString(),
  }, "batch_id, tx_hash");
}

async function onOwnershipTransferred(batchId, from, to, location, timestamp, event) {
  console.log(`[Event] OwnershipTransferred ${from.slice(0,8)}… → ${to.slice(0,8)}…`);
  await upsertBlockchainRecord("blockchain_transfers", {
    batch_id:    batchId,
    from_addr:   from.toLowerCase(),
    to_addr:     to.toLowerCase(),
    location:    location,
    recorded_at: new Date(Number(timestamp) * 1000).toISOString(),
    tx_hash:     event.log.transactionHash,
    block_number: Number(event.log.blockNumber),
    created_at:  new Date().toISOString(),
  }, "batch_id, tx_hash");
}

async function onFormulationCreated(formulationId, productName, manufacturer, timestamp, event) {
  console.log(`[Event] FormulationCreated id=${formulationId.slice(0,12)}…`);
  await upsertBlockchainRecord("blockchain_formulations", {
    formulation_id: formulationId,
    product_name:   productName,
    manufacturer:   manufacturer.toLowerCase(),
    recorded_at:    new Date(Number(timestamp) * 1000).toISOString(),
    tx_hash:        event.log.transactionHash,
    block_number:   Number(event.log.blockNumber),
    created_at:     new Date().toISOString(),
  }, "formulation_id");
}

// ─── Event Listener Setup ─────────────────────────────────────────────────────

function startEventListeners() {
  const contract = getContract();

  console.log("\n[Listener] 👂  Listening for on-chain events…");

  contract.on("BatchCreated",          onBatchCreated);
  contract.on("CollectionRecorded",    onCollectionRecorded);
  contract.on("ProcessingStepAdded",   onProcessingStepAdded);
  contract.on("QualityTestRecorded",   onQualityTestRecorded);
  contract.on("OwnershipTransferred",  onOwnershipTransferred);
  contract.on("FormulationCreated",    onFormulationCreated);

  provider.on("error", (err) => {
    console.error("[Provider] Error:", err.message);
  });
}

// ─── Historical Sync (on startup) ─────────────────────────────────────────────

async function syncHistoricalEvents() {
  const contract     = getContract();
  const latestBlock  = await provider.getBlockNumber();
  const fromBlock    = Math.max(0, latestBlock - 10_000); // last 10k blocks

  console.log(`\n[Sync] Syncing events from block ${fromBlock} → ${latestBlock}`);

  try {
    const batches = await contract.queryFilter("BatchCreated", fromBlock, latestBlock);
    console.log(`[Sync] Found ${batches.length} BatchCreated events`);
    for (const e of batches) {
      await onBatchCreated(e.args.batchId, e.args.herbName, e.args.collector, e.args.harvestDate, e.args.isSustainable, e);
    }

    const transfers = await contract.queryFilter("OwnershipTransferred", fromBlock, latestBlock);
    console.log(`[Sync] Found ${transfers.length} OwnershipTransferred events`);
    for (const e of transfers) {
      await onOwnershipTransferred(e.args.batchId, e.args.from, e.args.to, e.args.location, e.args.timestamp, e);
    }

    const tests = await contract.queryFilter("QualityTestRecorded", fromBlock, latestBlock);
    console.log(`[Sync] Found ${tests.length} QualityTestRecorded events`);
    for (const e of tests) {
      await onQualityTestRecorded(e.args.batchId, e.args.lab, e.args.passed, e.args.pesticideLevel, e.args.moistureContent, e.args.timestamp, e);
    }

    const formulations = await contract.queryFilter("FormulationCreated", fromBlock, latestBlock);
    console.log(`[Sync] Found ${formulations.length} FormulationCreated events`);
    for (const e of formulations) {
      await onFormulationCreated(e.args.formulationId, e.args.productName, e.args.manufacturer, e.args.timestamp, e);
    }

    console.log("[Sync] ✅ Historical sync complete");
  } catch (err) {
    console.error("[Sync] Error during historical sync:", err.message);
  }
}

// ─── Express API ──────────────────────────────────────────────────────────────

function createApp() {
  const app = express();
  app.use(cors());
  app.use(express.json());

  // ── Health check ────────────────────────────────────────────────────────────
  app.get("/health", (req, res) => {
    res.json({ status: "ok", contract: config.contractAddress, rpc: config.rpcUrl });
  });

  // ── Get batch provenance ────────────────────────────────────────────────────
  app.get("/api/provenance/:batchId", async (req, res) => {
    try {
      const contract = getContract();
      const prov = await contract.viewBatchProvenance(req.params.batchId);
      res.json({ ok: true, data: formatProvenance(prov) });
    } catch (err) {
      handleError(res, err);
    }
  });

  // ── Get batch summary ───────────────────────────────────────────────────────
  app.get("/api/batch/:batchId/summary", async (req, res) => {
    try {
      const contract = getContract();
      const [herbName, collector, harvestDate, isSustainable, qualityApproved, processingCount, transferCount]
        = await contract.getBatchSummary(req.params.batchId);
      res.json({ ok: true, data: {
        herbName, collector, harvestDate: Number(harvestDate),
        isSustainable, qualityApproved,
        processingCount: Number(processingCount),
        transferCount: Number(transferCount),
      }});
    } catch (err) {
      handleError(res, err);
    }
  });

  // ── Get transfer history ────────────────────────────────────────────────────
  app.get("/api/batch/:batchId/transfers", async (req, res) => {
    try {
      const contract = getContract();
      const transfers = await contract.getTransferHistory(req.params.batchId);
      res.json({ ok: true, data: transfers.map(formatTransfer) });
    } catch (err) {
      handleError(res, err);
    }
  });

  // ── Get all batch IDs ───────────────────────────────────────────────────────
  app.get("/api/batches", async (req, res) => {
    try {
      const contract = getContract();
      const ids = await contract.getAllBatchIds();
      res.json({ ok: true, data: ids });
    } catch (err) {
      handleError(res, err);
    }
  });

  // ── Check role ──────────────────────────────────────────────────────────────
  app.get("/api/role-check/:roleName/:address", async (req, res) => {
    try {
      const contract = getContract();
      const roleKey  = req.params.roleName.toUpperCase() + "_ROLE";
      const roleHash = await contract[roleKey]?.();
      if (!roleHash) return res.status(400).json({ ok: false, error: "Unknown role" });
      const hasIt = await contract.hasRole(roleHash, req.params.address);
      res.json({ ok: true, data: { role: req.params.roleName, address: req.params.address, hasRole: hasIt } });
    } catch (err) {
      handleError(res, err);
    }
  });

  // ── BACKEND-SIGNED TRANSACTIONS (requires BACKEND_PRIVATE_KEY) ─────────────
  // These are for server-side role management, not for user wallet transactions

  app.post("/api/admin/grant-role", async (req, res) => {
    try {
      const { roleName, address } = req.body;
      if (!roleName || !address) return res.status(400).json({ ok: false, error: "roleName and address required" });
      const contract = getSignerContract();
      const roleKey  = roleName.toUpperCase() + "_ROLE";
      const roleHash = await contract[roleKey]?.();
      if (!roleHash) return res.status(400).json({ ok: false, error: "Unknown role" });
      const tx      = await contract.grantSupplyChainRole(roleHash, address);
      const receipt = await tx.wait();
      // Update Supabase profile to reflect the new blockchain role
      await supabase.from("profiles").update({ blockchain_role_granted: true }).eq("wallet_address", address.toLowerCase());
      res.json({ ok: true, txHash: receipt.hash });
    } catch (err) {
      handleError(res, err);
    }
  });

  app.post("/api/admin/revoke-role", async (req, res) => {
    try {
      const { roleName, address } = req.body;
      const contract = getSignerContract();
      const roleKey  = roleName.toUpperCase() + "_ROLE";
      const roleHash = await contract[roleKey]?.();
      if (!roleHash) return res.status(400).json({ ok: false, error: "Unknown role" });
      const tx      = await contract.revokeSupplyChainRole(roleHash, address);
      const receipt = await tx.wait();
      res.json({ ok: true, txHash: receipt.hash });
    } catch (err) {
      handleError(res, err);
    }
  });

  return app;
}

// ─── Formatters ───────────────────────────────────────────────────────────────

function formatProvenance(p) {
  return {
    batchId:         p.batchId,
    herbName:        p.herbName,
    geoLatitude:     p.geoLatitude,
    geoLongitude:    p.geoLongitude,
    harvestDate:     Number(p.harvestDate),
    isSustainable:   p.isSustainable,
    currentOwner:    p.currentOwner,
    collector:       p.collector,
    processingSteps: p.processingSteps?.map(s => ({
      processType:      Number(s.processType),
      processorAddress: s.processorAddress,
      timestamp:        Number(s.timestamp),
      storageConditions: s.storageConditions,
      notes:            s.notes,
      facilityId:       s.facilityId,
      ipfsHash:         s.ipfsHash,
    })) ?? [],
    qualityTests:   p.qualityTests?.map(t => ({
      moistureContent:  Number(t.moistureContent),
      pesticideLevel:   Number(t.pesticideLevel),
      dnaAuthenticated: t.dnaAuthenticated,
      labAddress:       t.labAddress,
      passed:           t.passed,
      timestamp:        Number(t.timestamp),
      remarks:          t.remarks,
      ipfsHash:         t.ipfsHash,
    })) ?? [],
    transfers:      p.transfers?.map(formatTransfer) ?? [],
    hasPassedLatestQualityTest: p.hasPassedLatestQualityTest,
    queriedAt:      Number(p.provenanceQueriedAt),
  };
}

function formatTransfer(t) {
  return {
    from:          t.from,
    to:            t.to,
    batchId:       t.batchId,
    timestamp:     Number(t.timestamp),
    location:      t.location,
    notes:         t.notes,
    transferIndex: Number(t.transferIndex),
    ipfsHash:      t.ipfsHash,
  };
}

function handleError(res, err) {
  console.error("[API] Error:", err.message);
  const status = err.message?.includes("does not exist") ? 404 : 500;
  res.status(status).json({ ok: false, error: err.message ?? "Internal error" });
}

// ─── Database Migration Helper ─────────────────────────────────────────────────

/**
 * Run this function (or paste this SQL) in Supabase SQL editor to create
 * the tables needed for blockchain sync.
 */
const SUPABASE_MIGRATION_SQL = `
-- Blockchain sync tables for HerbChain
-- Run this once in your Supabase SQL editor.

CREATE TABLE IF NOT EXISTS blockchain_batches (
  id              BIGSERIAL PRIMARY KEY,
  batch_id        TEXT UNIQUE NOT NULL,   -- bytes32 hex
  herb_name       TEXT NOT NULL,
  collector       TEXT NOT NULL,          -- wallet address (lowercase)
  harvest_date    TIMESTAMPTZ,
  is_sustainable  BOOLEAN DEFAULT false,
  tx_hash         TEXT,
  block_number    BIGINT,
  created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS blockchain_collections (
  id          BIGSERIAL PRIMARY KEY,
  batch_id    TEXT UNIQUE REFERENCES blockchain_batches(batch_id),
  collector   TEXT NOT NULL,
  herb_species TEXT,
  recorded_at TIMESTAMPTZ,
  tx_hash     TEXT,
  block_number BIGINT,
  created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS blockchain_processing_steps (
  id           BIGSERIAL PRIMARY KEY,
  batch_id     TEXT REFERENCES blockchain_batches(batch_id),
  step_index   INT NOT NULL,
  process_type TEXT,
  processor    TEXT NOT NULL,
  recorded_at  TIMESTAMPTZ,
  tx_hash      TEXT,
  block_number BIGINT,
  created_at   TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(batch_id, step_index)
);

CREATE TABLE IF NOT EXISTS blockchain_quality_tests (
  id               BIGSERIAL PRIMARY KEY,
  batch_id         TEXT REFERENCES blockchain_batches(batch_id),
  lab_address      TEXT NOT NULL,
  passed           BOOLEAN NOT NULL,
  pesticide_level  INT DEFAULT 0,
  moisture_content INT DEFAULT 0,
  recorded_at      TIMESTAMPTZ,
  tx_hash          TEXT UNIQUE,
  block_number     BIGINT,
  created_at       TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS blockchain_transfers (
  id           BIGSERIAL PRIMARY KEY,
  batch_id     TEXT REFERENCES blockchain_batches(batch_id),
  from_addr    TEXT NOT NULL,
  to_addr      TEXT NOT NULL,
  location     TEXT,
  recorded_at  TIMESTAMPTZ,
  tx_hash      TEXT UNIQUE,
  block_number BIGINT,
  created_at   TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS blockchain_formulations (
  id             BIGSERIAL PRIMARY KEY,
  formulation_id TEXT UNIQUE NOT NULL,
  product_name   TEXT NOT NULL,
  manufacturer   TEXT NOT NULL,
  recorded_at    TIMESTAMPTZ,
  tx_hash        TEXT,
  block_number   BIGINT,
  created_at     TIMESTAMPTZ DEFAULT NOW()
);

-- Add blockchain columns to existing profiles table (if not already there)
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS wallet_address TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS blockchain_role_granted BOOLEAN DEFAULT false;

-- Add tx_hash columns to existing application tables
ALTER TABLE collections ADD COLUMN IF NOT EXISTS tx_hash TEXT;
ALTER TABLE collections ADD COLUMN IF NOT EXISTS blockchain_synced BOOLEAN DEFAULT false;
ALTER TABLE collections ADD COLUMN IF NOT EXISTS synced_at TIMESTAMPTZ;
`;

// ─── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const line = "═".repeat(60);
  console.log(line);
  console.log("  HerbChain — Backend Blockchain Sync Service");
  console.log(line);
  console.log("  RPC URL  :", config.rpcUrl);
  console.log("  Contract :", config.contractAddress);
  console.log("  Supabase :", config.supabaseUrl);
  console.log(line);

  // Verify connection
  try {
    const blockNumber = await provider.getBlockNumber();
    const network     = await provider.getNetwork();
    console.log(`\n  ✅  Connected to network chainId=${network.chainId} block=${blockNumber}`);
  } catch (err) {
    console.error("  ❌  Cannot connect to RPC:", err.message);
    console.error("      Make sure Hardhat node is running: npx hardhat node");
    process.exit(1);
  }

  // Print migration SQL if Supabase tables need setup
  if (process.argv.includes("--print-sql")) {
    console.log("\n" + SUPABASE_MIGRATION_SQL);
    process.exit(0);
  }

  // Historical sync
  await syncHistoricalEvents();

  if (process.env.SYNC_ONLY === "1") {
    console.log("\nSync-only mode — exiting.");
    process.exit(0);
  }

  // Start real-time event listener
  startEventListeners();

  // Start Express server
  const app  = createApp();
  const port = config.port;
  app.listen(port, () => {
    console.log(`\n  🚀  API running on http://localhost:${port}`);
    console.log("  Endpoints:");
    console.log("    GET  /health");
    console.log("    GET  /api/batches");
    console.log("    GET  /api/provenance/:batchId");
    console.log("    GET  /api/batch/:batchId/summary");
    console.log("    GET  /api/batch/:batchId/transfers");
    console.log("    GET  /api/role-check/:roleName/:address");
    console.log("    POST /api/admin/grant-role");
    console.log("    POST /api/admin/revoke-role");
  });
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});

module.exports = { formatProvenance, formatTransfer, SUPABASE_MIGRATION_SQL };
